import datetime
from typing import Optional
from sqlmodel import SQLModel, Field


class Resume(SQLModel, table=True):
    """
    The entity representing a resume uploaded and its AI feedback.
    @attribute id: The id of the resume.
    @attribute created_at: The date and time the resume was created.
    @attribute original_filename: The original filename of the resume.
    @attribute job_title: The job title of the resume.
    @attribute resume_html: The html text extracted from the resume.
    @attribute feedback_text: The feedback text of the resume.
    @attribute revised_html: The html text of the resume after the feedback.
    @attribute result_pdf_path: The path to the pdf file of the resume generated by the AI.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    original_filename: str
    job_title: Optional[str] = None
    resume_html: Optional[str] = None
    feedback_text: Optional[str] = None
    revised_html: Optional[str] = None
    result_pdf_path: Optional[str] = None
