"""initial tables

Revision ID: 57a85f2a473b
Revises:
Create Date: 2025-06-15 14:41:02.813566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "57a85f2a473b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "original_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("job_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resume_html", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("feedback_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("revised_html", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result_pdf_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume")
    # ### end Alembic commands ###
